export const AI_MODELS = [
  {
    id: "gemini-3.5-flash-lite",
    provider: "google",
    rpm: 15,
    rpd: 500,
    tpm: 250_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: false,
    },
    priority: 1,
  },
  {
    id: "gemini-3.1-flash-lite",
    provider: "google",
    rpm: 15,
    rpd: 500,
    tpm: 250_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: false,
    },
    priority: 2,
  },
  {
    id: "gemini-3.7-flash",
    provider: "google",
    rpm: 5,
    rpd: 20,
    tpm: 250_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: true,
    },
    priority: 3,
  },
  {
    id: "gemini-3.6-flash",
    provider: "google",
    rpm: 5,
    rpd: 20,
    tpm: 250_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: true,
    },
    priority: 4,
  },
  {
    id: "gemini-3.5-flash",
    provider: "google",
    rpm: 5,
    rpd: 20,
    tpm: 250_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: true,
    },
    priority: 5,
  },
  {
    id: "gemini-3-flash-preview",
    provider: "google",
    rpm: 5,
    rpd: 20,
    tpm: 250_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: true,
    },
    priority: 6,
  },
  {
    id: "deepseek-ai/deepseek-v4-flash-0731",
    provider: "nvidia",
    rpm: 40,
    rpd: null,
    tpm: null,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: true,
    },
    priority: 7,
  },
  {
    id: "openrouter/free",
    provider: "openrouter",
    rpm: null,
    rpd: 50,
    tpm: null,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: true,
    },
    priority: 8,
  },
  {
    id: "llama-3.3-70b-versatile",
    provider: "groq",
    rpm: 30,
    rpd: 1_000,
    tpm: 12_000,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: false,
    },
    priority: 9,
  },
  {
    id: "mistral-small-latest",
    provider: "mistral",
    rpm: null,
    rpd: null,
    tpm: null,
    capabilities: {
      toolCalling: true,
      webSearch: false,
      generalChat: true,
      storeData: true,
      listWriter: false,
    },
    priority: 10,
  },
] as const;

export type AIModel = (typeof AI_MODELS)[number];
